---
name: "CircleCI artifact handling"
on: [status]
jobs:
  circleci_artifacts_redirector_job:
    if: "${{ github.event.context == 'ci/circleci: build_docs' }}"
    permissions:
      statuses: write
    runs-on: ubuntu-latest
    name: Run CircleCI artifacts redirector
    steps:
      - name: GitHub Action step
        uses:
          scientific-python/circleci-artifacts-redirector-action@4e13a10d89177f4bfc8007a7064bdbeda848d8d1  # v1.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLECI_TOKEN }}
          artifact-path: 0/docs/_build/html/index.html
          circleci-jobs: build_docs
          job-title: View the built docs
